debug: false

spring:
  application:
    name: kafka-rest-debezium-listener
  kafka:
    bootstrap-servers: localhost:9092 
    consumer:
      group-id: debezium
      auto-offset-reset: earliest
    listener:
         topic: dbserver1.inventory.customers  
 
logging:
  file: logs/app.log
  
management.endpoints.web.exposure.include: "*"
  