debug: false

spring:
  application:
    name: kafka-rest-debezium-register-connector
  kafka:
    consumer:
      group-id: debezium
      auto-offset-reset: earliest

server:
   servlet:
      contextPath: /kafka-register
   port: 8082   
 
logging:
  file: logs/app.log
  
kafka:
  bootstrap-servers: localhost:9092 
  connector:
    url: http://localhost:8083/connectors/
    name: inventory-connector
    config-file: inventory-connector.properties 
    listener:
         topic: dbserver1.inventory.customers

management.endpoints.web.exposure.include: "*"
  