debug: false

spring:
   application:
      name: connector-kafka-spring-boot-listener-consumer
   kafka:
      bootstrap-servers: localhost:9092
      consumer:
         group-id: example-group
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  topic:
    messages: topic-messages
    events: topic-events

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG