spring:
  kafka:
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092
    consumer:
       group-id: example-group
       auto-offset-reset: earliest

app:
  topic:
    example1: topic-1
    example2: topic-2

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG