debug: false

spring:
   application:
      name: demo-crud-debezium-mysql-boot
   datasource:
      url: jdbc:mysql://localhost:3306/inventory
      username: mysqluser
      password: mysqlpw 
      driver-class-name: com.mysql.jdbc.Driver
      jpa.hibernate.ddl-auto: update
      jpa.show-sql: true
      jpa.properties.hibernate.format_sql: true
      

server:
   servlet:
      contextPath: /kafka-cdc


logging:
  file: logs/app.log
  
management.endpoints.web.exposure.include: "*"
  