debug: false

spring:
   application:
      name: kafka-rest-sender-connector

server:
   servlet:
      contextPath: /kafka-connector
   port: 8081

app:
   version: Draft

spring:
  kafka:
    bootstrap-servers: localhost:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  topic:
    messages: topic-messages
    events: topic-events

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG


---    
spring:
   profiles: dev

server:
   port: 8090


---
spring:
   profiles: prod

server:
   port: 9090
    